//USER TYPES
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const REMOVE_USER = 'REMOVE_USER';

//GROUP TYPES
export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';

//LIST USER TYPES
export const GET_LIST_USER = 'GET_LIST_USER';
export const GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS';
export const GET_LIST_USER_FAIL = 'GET_LIST_USER_FAIL';
